[theme]
primaryColor="#1f77b4"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[client]
# Show toolbar only when hovering
toolbarMode="minimal"

[server]
# Prevent CORS issues
enableCORS=false
enableXsrfProtection=true

[browser]
# Automatically open browser
gatherUsageStats=false